name: Fetch Wittgenstein Nachlass

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    name: Fetch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - name: Install xmllint
        run: apt-get update && apt-get install -y libxml2-utils
      - name: Install Dart Dependencies
        run: pub get
      - name: Fetch Nachlass
        run: pub run bin/main.dart
      - name: Commit
        env:
          COMMIT_AUTHOR: Alois Pichler <Alois.Pichler@uib.no>
        run: sh ./commit.sh
